import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

/**
 * Escapes CSV fields
 */
const escapeCSV = (field) => {
    if (field === null || field === undefined) return '';
    const str = String(field);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
        return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
};

/**
 * Export to CSV
 */
export const exportToCSV = (data, filename, headers) => {
    const csvContent = [
        headers.join(","),
        ...data.map(row => row.map(escapeCSV).join(","))
    ].join("\n");

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};

/**
 * Export to Excel (proper XLSX)
 */
export const exportToExcel = (data, filename, headers) => {
    // Create a new workbook and worksheet
    const worksheet = XLSX.utils.aoa_to_sheet([headers, ...data]);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");

    // Write file
    XLSX.writeFile(workbook, `${filename}.xlsx`);
};

/**
 * Export to PDF (Designed with RIDEN theme)
 */
export const exportToPDF = (data, filename, headers, title) => {
    const doc = jsPDF({
        orientation: 'landscape',
        unit: 'mm',
        format: 'a4'
    });

    // Theme Colors
    const primaryColor = [209, 0, 0]; // #D10000
    const lightGray = [107, 114, 128]; // #6B7280

    // Header Background
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 297, 45, 'F');

    // Portal Logo Text
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.text("RIDEN", 15, 22);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.text("ADMIN DASHBOARD PORTAL", 15, 32);

    // Report Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(title.toUpperCase(), 15, 60);

    // Metadata
    doc.setTextColor(...lightGray);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by: Riden Admin`, 15, 68);
    doc.text(`Date & Time: ${new Date().toLocaleString()}`, 15, 73);

    // Horizontal Line
    doc.setDrawColor(229, 231, 235);
    doc.line(15, 80, 282, 80);

    // Table
    autoTable(doc, {
        startY: 90,
        head: [headers],
        body: data,
        theme: 'striped',
        headStyles: {
            fillColor: primaryColor,
            textColor: [255, 255, 255],
            fontSize: 10,
            fontStyle: 'bold',
            halign: 'center'
        },
        bodyStyles: {
            fontSize: 9,
            cellPadding: 3
        },
        alternateRowStyles: {
            fillColor: [255, 245, 245] // Very light red
        },
        margin: { left: 15, right: 15 },
        styles: {
            overflow: 'linebreak',
            font: 'helvetica'
        }
    });

    // Page Numbering
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${totalPages}`, 282, 200, { align: 'right' });
        doc.text("© 2026 RIDEN TECH SOLUTIONS. CONFIDENTIAL DOCUMENT.", 15, 200);
    }

    doc.save(`${filename}.pdf`);
};
